### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by F1atline** [sap-labs-france/ev-mobile#965]
Hi, have some problem with biuld, below cmd log:

> ev-mobile@2.6.10 android
> cross-env TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling react-native run-android

info Starting JS server...
info Installing the app...
Starting a Gradle Daemon, 4 incompatible Daemons could not be reused, use --status for details

> Task :react-native-gradle-plugin:compileKotlin
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (10, 37): 'BaseVariant
' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (119, 30): 'BaseVarian
t' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (135, 26): 'BaseVarian
t' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (157, 32): 'BaseVarian
t' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (163, 31): 'BaseVarian
t' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (171, 36): 'BaseVarian
t' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactPlugin.kt: (114, 48): 'reactRoot: Di
rectoryProperty' is deprecated. reactRoot was confusing and has been replace with root to point to your root project and reactNativeDir to point to t
he folder of the react-native NPM package
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (10, 37): 'Applicat
ionVariant' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (11, 37): 'BaseVari
ant' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (12, 37): 'LibraryV
ariant' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (27, 51): 'BaseVari
ant' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (130, 12): 'Applica
tionVariant' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (131, 12): 'Library
Variant' is deprecated. Deprecated in Java
w: C:\WRK\coding\repos\ev-mobile\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (251, 14): 'BaseVar
iant' is deprecated. Deprecated in Java

> Configure project :app
WARNING:The option setting 'android.disableResourceValidation=true' is experimental.
The current default is 'false'.
5 actionable tasks: 3 executed, 2 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > The file 'C:\WRK\coding\repos\ev-mobile\android\local.properties' could not be found

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 54s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > The file 'C:\WRK\coding\repos\ev-mobile\android\local.properties' could not be found

* Try:
PS C:\WRK\coding\repos\ev-mobile> npm run android

> ev-mobile@2.6.10 android
> cross-env TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling react-native run-android

info Starting JS server...
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
5 actionable tasks: 5 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > The file 'C:\WRK\coding\repos\ev-mobile\android\local.properties' could not be found

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > The file 'C:\WRK\coding\repos\ev-mobile\android\local.properties' could not be found

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s

    at makeError (C:\WRK\coding\repos\ev-mobile\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\WRK\coding\repos\ev-mobile\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\WRK\coding\repos\ev-mobile\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\WRK\coding\repos\ev-mobile\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
PS C:\WRK\coding\repos\ev-mobile

**Comment by F1atline** [comment]
I added local.properties file but failed on next task:

> Task :app:processDebugMainManifest FAILED
package="com.emobility" found in source AndroidManifest.xml: C:\WRK\coding\repos\ev-mobile\android\app\src\main\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
158 actionable tasks: 153 executed, 5 up-to-date
C:\WRK\coding\repos\ev-mobile\android\app\src\main\AndroidManifest.xml:23:9-42 Error:
        Attribute meta-data#com.google.android.geo.API_KEY@value at AndroidManifest.xml:23:9-42 requires a placeholder substitution but no value for <GOOGLE_API_KEY> is provided.
C:\WRK\coding\repos\ev-mobile\android\app\src\debug\AndroidManifest.xml Error:
        Validation failed, exiting

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.d Completed in 58ms
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 36s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
C:\WRK\coding\repos\ev-mobile\android\app\src\main\AndroidManifest.xml:23:9-42 Error:
        Attribute meta-data#com.google.android.geo.API_KEY@value at AndroidManifest.xml:23:9-42 requires a placeholder substitution but no value for <GOOGLE_API_KEY> is provided.
C:\WRK\coding\repos\ev-mobile\android\app\src\debug\AndroidManifest.xml Error:
        Validation failed, exiting

FAILURE: Build completed with 2 failures.

-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

**Comment by An-nasMs1817120893** [comment]
im also having this issue , has anyone find the solutions yet ?

**Comment by F1atline** [comment]
> im also having this issue , has anyone find the solutions yet ?

What operating system are you using?

**Comment by An-nasMs1817120893** [comment]
im using windows 11 , btw you might want to add the google API key , you can follow my issue here https://github.com/sap-labs-france/ev-mobile/issues/975

after you add the google API key , the app can be build successfully but it seems like the app will freeze on the main page and I haven't able to find the solutions yet , the new issue is here https://github.com/sap-labs-france/ev-mobile/issues/976
